// Generated by https://quicktype.io

export interface IQuestionPost {
  answerId: number;
  answerContents: string;
  createdAt: string;
  modifiedAt: string;
  user: User;
}

export interface User {
  userId: number;
  email: string;
  userName: string;
}
