Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{AWS RDS EndPoint}:3306/pre_project_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
#    username: {RDS Mysql Admin id}
#    password: {RDS Mysql Admin password}

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG


server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
  servlet:
    encoding:
      force-response: true

jwt:
#  secret-key: {AWS jwt secret-key}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
