Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pre_project_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG


server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12


jwt:
  secret-key: dlatlqlalfqjsghdlatlqlalfqjsghdlatlqlalfqjsghdlatlqlalfqjsghdlatlqlalfqjsghdlatlqlalfqjsghdlatlqlalfqjsgh
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

