Spring:
  config:
    import: 'aws-parameterstore:'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.url}:3306/pre_project_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

aws:
  paramstore:
    prefix: /spring-boot-aws
    name: cloud-parameter-store
    enabled: true
    profile-separator: _
#    AWS_RDS_Endpoint: ${/spring-boot-aws/cloud-parameter-store/spring.datasource.url}
#    RDS_Mysql_Admin_id: ${/spring-boot-aws/cloud-parameter-store/spring.datasource.username}
#    RDS_Mysql_Admin_password: ${/spring-boot-aws/cloud-parameter-store/spring.datasource.password}
#    AWS_jwt_secret_key: ${/spring-boot-aws/cloud-parameter-store/jwt.secret-key}

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG



server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
  servlet:
    encoding:
      force-response: true

jwt:
  secret-key: ${jwt.secret-key}
  access-token-expiration-minutes: 180
#  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
